### PR TITLE
ADDED_SOLN

### PR DESCRIPTION
**Pull request by SUBZZGITHUB**

### CODE REVIEW

**Comment by Raj2367** [comment]
Your Solution is correct but The worst time Complexity is O(n2).
Eg: arr=[1,1,1,1,1,7] and sum=8
So try to come up with a solution of O(n).

**Comment by Raj2367** [comment]
> changed the array to a sorted one

no need to make the input array as sorted one. I gave just an example, where the time complexity is O(n2). So change your code, instead of changing the input array.

**Comment by SUBZZGITHUB** [comment]
sir i avoided nested loops so as to reduce the time complexity, Sir just check once

**Comment by Raj2367** [comment]
Yes, Now your solution is good and the worst time complexity is O(n). Good job!

**Pull request merged**
